### ISSUE TITLE
Update devtools solution with Selenium 4.23.1

### ISSUE THREAD

**Issue by Dlankheet** [markhobson/docker-maven-chrome#57]
We have our pipeline running with the image for JDK 21 with selenium 4.23.1.
But the chrome drivers are too old to run with this is version. 
Is it possible to update them to the latest version?

**Comment by markhobson** [comment]
Hi, there's a few tasks in order to do this:

1. Upgrade Chrome to 128.0.6613.119
1. Upgrade ChromeDriver to 128.0.6613.119
1. Upgrade Selenium in the test project & demo to 4.24.0 to work with Chrome 128
1. Drop JDK 8 support since Selenium moved to Java 11 in 4.14.0
1. Investigate and resolve the failing test

There's also a PR #58 that has attempted to start this.

**Comment by markhobson** [comment]
Upgraded ChromeDriver to 130.0.6723.58.
